### ISSUE TITLE
UI Task

### ISSUE THREAD

**Issue by doggygit** [NemoNessuno/BattleForBerlin#1]
- [x] Mutex für Layer (Wahlbezirke, Wahlkreise)
- [x] onClick Handler für Wahlbezirke
- [x] onLoad fetchData
- [ ] Ansicht der Sieger/Verlierer
  - Wenn die Leute nach offizieller Wahl gewonnen haben aber nach gerrymandering nicht mehr -> roter rahmen bzw. grüner Rahmen wenn anders rum
  - im selben Fenster "potentaten" anzeigen
- [x] stepper
- [x] Einfärbung von Shapes (nach Gewinnern)

**Comment by NemoNessuno** [comment]
Ansicht der Sieger/Verlierer won't be implemented.
